; Generated by VUC 2004.1

.init_vf_all
.init_vi_all
.syntax new

.vu

--enter
--endenter

.include "vcl_sml.i"
.include "std.i"

.macro _TransformVertex vertexAddr_004 saveAddr_005 
  lq             vertex_001, 0(\vertexAddr_004)
  iaddiu         \vertexAddr_004, \vertexAddr_004, 1
  _ftoi4         vertex_001 vertex_001 
  sq             vertex_001, 0(\saveAddr_005)
  iaddiu         \saveAddr_005, \saveAddr_005, 1
L_001_RETURN\@:
.endm

.macro _main vuMem_006 
  _xtop          dataAddr_007 
  iaddiu         vertexAddr_008, dataAddr_007, 1
  iaddiu         primAddr_009, dataAddr_007, 256
  iaddiu         saveAddr_010, dataAddr_007, 257
  iaddiu         vertCount_002, vi00, 3
  lq             tmp_030, 0(dataAddr_007)
  sq             tmp_030, 0(primAddr_009)
  iaddiu         i_003, vi00, 0
L_004_FOR_START\@:
  isub           cmp_035, i_003, vertCount_002
  ibltz          cmp_035, L_005_CMP_TRUE\@
  iaddiu         tmp_034, vi00, 0
  b              L_006_CMP_END\@
L_005_CMP_TRUE\@:
  iaddiu         tmp_034, vi00, 1
L_006_CMP_END\@:
  ibeq           tmp_034, vi00, L_003_FOR_END\@
  _TransformVertex vertexAddr_008 saveAddr_010 
  iaddiu         i_003, i_003, 1
  b              L_004_FOR_START\@
L_003_FOR_END\@:
  _xgkick        primAddr_009 
L_002_RETURN\@:
.endm

VUC_BEGIN:
  _main vi00
VUC_END:

--exit
--endexit
