; Generated by VUC 2004.1

.init_vf_all
.init_vi_all
.syntax new

.vu

--enter
--endenter

.include "vcl_sml.i"
.include "std.i"

.macro _main vuMem_001 
  _xtop          dataAddr_002 
  _xgkick        dataAddr_002 
L_001_RETURN\@:
.endm

VUC_BEGIN:
  _main vi00
VUC_END:

--exit
--endexit
