LIB             =tc
OBJS            =\
                ctype \
                errno \
                fcntl \
                pthread \
                srr \
                stdlib \
                string \
                unistd \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
