include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


LIB             =apps
OBJS            =\
                msgServer \
                nameServer \
                testSRR \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
