include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


OBJ             =apps
OBJS            =\
                fileServer \
                msgServer \
                testSRR \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
