include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


INCL_PATH       =\
                ../../libtwl \

LIB             =apps
OBJS            =\
                crate \
                desktop \
                glDemo1 \
                glDemo2 \
                main \
                mouse \
                taskBar \
                window \
                windowManager \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
