include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


INCL_PATH       =\
                ../../libtwl \

LIB             =apps
OBJS            =\
                desktop \
                glDemo1 \
                pyramid \
                main \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
