MAKEFLAGS	+=--no-print-directory -s


all:
	make -f Makefile all ARCH=mips TARGET=ps2-ee
	make -f Makefile all ARCH=mips TARGET=ps2-iop

clean:
	make -f Makefile clean ARCH=mips TARGET=ps2-ee
	make -f Makefile clean ARCH=mips TARGET=ps2-iop

run:
	ps2client -t 1 -h 192.168.1.10 execiop host:bin/ps2-iop/Bricks.elf.irx
	ps2client -t 1 -h 192.168.1.10 execee  host:bin/ps2-ee/Bricks.elf
