MAKEFLAGS	+=--no-print-directory -s


all: all9dirs bin/nds9/Bricks.nds

clean:
	make -f Makefile clean ARCH=arm TARGET=nds9

bin/nds9/Bricks.nds: bin/nds9/Bricks.bin
	@echo [NDS] $@
	ndstool -c $@ -9 bin/nds9/Bricks.bin -b bin/nds/banner.bmp "Bricks-OS;;" -o bin/nds/logo.bmp -g BRKS OS BRICKS-OS

bin/nds9/Bricks.bin: bin/nds9/Bricks.elf
	@echo [BIN] $@
	arm-eabi-objcopy -O binary $< $@

all9dirs:
	make -f Makefile all ARCH=arm TARGET=nds9
