MAKEFLAGS	+=--no-print-directory -s


all:
	make -f Makefile all ARCH=mips TARGET=ps2-ee

clean:
	make -f Makefile clean ARCH=mips TARGET=ps2-ee

run:
	ps2client -t 1 -h 192.168.1.10 execee host:bin/ps2-ee/Bricks.elf
