MAKEFLAGS	+=--no-print-directory -s


all:
	make -f Makefile all ARCH=i386 TARGET=pc

clean:
	make -f Makefile clean ARCH=i386 TARGET=pc

floppy:
	sudo mount bin/pc/floppy.img bin/pc/floppy -o loop
	sudo cp bin/pc/Bricks.elf bin/pc/floppy/boot/kernel/Bricks.elf
	sudo umount bin/pc/floppy

grub:
	sudo cp bin/pc/Bricks.elf /boot/Bricks.elf

