MAKEFLAGS	+=--no-print-directory -s


all:
	make -f Makefile all ARCH=arm TARGET=nds7
	make -f Makefile all ARCH=arm TARGET=nds9
	arm-eabi-objcopy -O binary bin/nds7/Bricks.elf bin/nds7/Bricks.bin
	arm-eabi-objcopy -O binary bin/nds9/Bricks.elf bin/nds9/Bricks.bin
	ndstool -c bin/nds9/Bricks.nds -9 bin/nds9/Bricks.bin -7 bin/nds7/Bricks.bin

clean:
	make -f Makefile clean ARCH=arm TARGET=nds7
	make -f Makefile clean ARCH=arm TARGET=nds9
