LIBS		+=\
		 archnds \
		 archarm \

LIB		=arch
OBJS		=\
		 support\
                 isr\
                 ds9Arch\
		 ds9IRQ\
		 ds9Video\
		 dsTimer\
		 dsCart\


INCL_PATH	+=\
		 $(DEVKITPRO)/libnds/include\
		 ../common\


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
