LIBS            +=\
                archnds \

LIB             =arch
OBJS            =\
                support \
                isr \
                arch \
                irq \
                ds9Video \
                dsCart \

#                dsTimer \

INCL_PATH       +=\
                $(DEVKITPRO)/libnds/include \
                ../common \


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
