include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


LIB             =bwm
OBJS            =\
                bwm \


OBJS-$(CONFIG_GL)                  += testGLF testGLFx pyramid cube crate


include $(BRICKS_ROOT)/include/makeinclude/rules.user
