include $(BRICKS_ROOT)/arch/$(ARCH)/config.$(TARGET)


LIB             =bwm
OBJS            =\
                bwm \

DEFINITIONS-$(CONFIG_GL)           += CONFIG_GL


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
