include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


OBJ             =apps
OBJS            =\
                main \
                modPlayer \
                SndData_c \
                SndData_s \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
