#----------------------------------------------------------------------------
ifeq ($(strip $(ARCH)),)
  $(error "ARCH not specified")
endif
ifeq ($(strip $(TARGET)),)
  $(error "TARGET not specified")
endif

#----------------------------------------------------------------------------
ifndef VDIR
VDIR            =obj-$(TARGET)/
endif
ifndef VSHDIR
  VSHDIR        =shobj-$(TARGET)/
endif
ifndef ELF_PATH
  ELF_PATH      =$(BRICKS_ROOT)/bin/$(TARGET)/
endif
ifndef LIB_PATH
  LIB_PATH      =$(BRICKS_ROOT)/lib/$(TARGET)/
endif

#----------------------------------------------------------------------------
MY_ELF          =$(addprefix $(ELF_PATH),$(addsuffix .elf,$(ELF)))
MY_INCL_PATH    =$(addprefix -I,$(INCL_PATH))
MY_LIB          =$(addprefix $(LIB_PATH)lib,$(addsuffix .a,$(LIB)))
MY_LIBS         =$(addprefix -l,$(LIBS))
MY_LIBS_PATH    =$(addprefix -L,$(LIBS_PATH))
MY_OBJS         =$(addprefix $(VDIR),$(addsuffix .o,$(OBJS)))

#----------------------------------------------------------------------------
MY_INCL_PATH    += \
                -I. \
                -I$(BRICKS_ROOT)/include \
                -I$(BRICKS_ROOT)/include/include-$(ARCH) \
                -I$(BRICKS_ROOT)/include/include-$(ARCH)/include-$(TARGET) \
                -I$(BRICKS_ROOT)/include/posix \
                -I$(BRICKS_ROOT)/include/stl \

MY_LIBS_PATH	+= \
                -L$(BRICKS_ROOT)/lib/$(TARGET) \

#----------------------------------------------------------------------------
CFLAGS          =\
                -O2 \
                -Wall \

CXXFLAGS        =\
                -O2 \
                -Wall \
                -fno-rtti \
                -fno-exceptions \

#----------------------------------------------------------------------------
include $(BRICKS_ROOT)/include/makeinclude/Makefile.rules.$(TARGET)

#----------------------------------------------------------------------------
AS              =$(CROSS_COMPILE)as
LD              =$(CROSS_COMPILE)ld
CC              =$(CROSS_COMPILE)gcc
CPP             =$(CROSS_COMPILE)g++
CXX             =$(CROSS_COMPILE)g++
AR              =$(CROSS_COMPILE)ar
NM              =$(CROSS_COMPILE)nm
STRIP           =$(CROSS_COMPILE)strip
OBJCOPY         =$(CROSS_COMPILE)objcopy
OBJDUMP         =$(CROSS_COMPILE)objdump
AWK             =awk

#----------------------------------------------------------------------------
# ACE, macros.GNU
#----------------------------------------------------------------------------
include $(BRICKS_ROOT)/include/makeinclude/macros.GNU

#----------------------------------------------------------------------------
include $(BRICKS_ROOT)/include/makeinclude/rules.local.BRICKS

#----------------------------------------------------------------------------
# ACE, rules.nested.GNU
#----------------------------------------------------------------------------
include $(BRICKS_ROOT)/include/makeinclude/rules.nested.GNU
