#----------------------------------------------------------------------------
ifeq ($(strip $(ARCH)),)
  $(error "ARCH not specified")
endif
ifeq ($(strip $(TARGET)),)
  $(error "TARGET not specified")
endif

#----------------------------------------------------------------------------
ifndef VDIR
VDIR            =obj-$(TARGET)/
endif
ifndef VSHDIR
  VSHDIR        =shobj-$(TARGET)/
endif
ifndef ELF_PATH
  ELF_PATH      =$(BRICKS_ROOT)/bin/$(TARGET)/
endif
ifndef LIB_PATH
  LIB_PATH      =$(BRICKS_ROOT)/lib/$(TARGET)/
endif

#----------------------------------------------------------------------------
MY_DEFINITIONS  =$(addprefix -D,$(DEFINITIONS))
MY_ELF          =$(addprefix $(ELF_PATH),$(addsuffix .elf,$(ELF)))
MY_INCL_PATH    =$(addprefix -I,$(INCL_PATH))
MY_LIB          =$(addprefix $(LIB_PATH)lib,$(addsuffix .a,$(LIB)))
MY_LIBS         =$(addprefix -l,$(LIBS))
MY_LIBS_DEP     =$(addprefix $(LIB_PATH)lib,$(addsuffix .a,$(LIBS)))
MY_LIBS_PATH    =$(addprefix -L,$(LIBS_PATH))
MY_OBJ          =$(addprefix $(LIB_PATH)lib,$(addsuffix .a,$(OBJ)))
MY_OBJS         =$(addprefix $(VDIR),$(addsuffix .o,$(OBJS)))
MY_OBJS         +=$(addprefix $(VDIR),$(addsuffix .o,$(OBJS-y)))

#----------------------------------------------------------------------------
MY_INCL_PATH    += \
                -I. \
                -I./include \

MY_LIBS_PATH    += \
                -L$(BRICKS_ROOT)/lib/$(TARGET) \

#----------------------------------------------------------------------------
CFLAGS          =\
                -O2 \
                -Wall \
                -fno-strict-aliasing \
                $(MY_DEFINITIONS) \

CXXFLAGS        =\
                -O2 \
                -Wall \
                -fno-rtti \
                -fno-exceptions \
                -fno-strict-aliasing \
                $(MY_DEFINITIONS) \

LDFLAGS         =\
                -r \

ARFLAGS         =\
                -rc \

#----------------------------------------------------------------------------
include $(BRICKS_ROOT)/include/makeinclude/Makefile.rules.$(TARGET)

#----------------------------------------------------------------------------
AS              =$(CROSS_COMPILE)as
LD              =$(CROSS_COMPILE)ld
CC              =$(CROSS_COMPILE)gcc
CXX             =$(CROSS_COMPILE)g++
AR              =$(CROSS_COMPILE)ar
NM              =$(CROSS_COMPILE)nm
STRIP           =$(CROSS_COMPILE)strip
OBJCOPY         =$(CROSS_COMPILE)objcopy
OBJDUMP         =$(CROSS_COMPILE)objdump
AWK             =awk

#----------------------------------------------------------------------------
# ACE, macros.GNU
#----------------------------------------------------------------------------
include $(BRICKS_ROOT)/include/makeinclude/macros.GNU

#----------------------------------------------------------------------------
include $(BRICKS_ROOT)/include/makeinclude/rules.local.BRICKS

#----------------------------------------------------------------------------
# ACE, rules.nested.GNU
#----------------------------------------------------------------------------
include $(BRICKS_ROOT)/include/makeinclude/rules.nested.GNU
