LIBS		+=archarm
LIB		=arch
OBJS		=\
                 support \
                 isr \
		 gbaArch \
		 gbaIRQ \
		 gbaVideo \
		 gbaKeyboard


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
