LIB             =arch
OBJS            =\
                support \
                isr \
                arch \
                irq \
                gbaVideo \
                gbaKeyboard \
                serial \


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
