LIB             =tace

OBJS            =\
                OS \
                Task \
                Thread \
                Thread_Manager \
                Time_Value \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
