# Hardware capabilities
CONFIG_FPU=y

# Kernel interface
#CONFIG_DIRECT_ACCESS_KERNEL=y
#CONFIG_DIRECT_ACCESS_KERNEL_FUNC=y

# File System
#CONFIG_FILESYSTEM=y
#CONFIG_FS_FAT=y
#CONFIG_PD_IBM=y

# Video configuration
#CONFIG_FRAMEBUFFER=y
#CONFIG_GL=y
#CONFIG_GL_MULTI_CONTEXT=y

# Library configuration
CONFIG_BUILTIN_MM=y
CONFIG_BUILTIN_LIBC=y
