ifeq ($(TARGET),gba)
  DIRS = common gba
endif
ifeq ($(TARGET),nds7)
  DIRS = common nds
endif
ifeq ($(TARGET),nds9)
  DIRS = common nds
endif


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
