INCL_PATH       +=\
                $(BRICKS_ROOT)/zlib \

LIB             =png

OBJS            =\
                png \
                pngerror \
                pnggccrd \
                pngget \
                pngmem \
                pngpread \
                pngread \
                pngrio \
                pngrtran \
                pngrutil \
                pngset \
                pngtrans \
                pngvcrd \
                pngwio \
                pngwrite \
                pngwtran \
                pngwutil \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
