include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


INCL_PATH       =\
                ../apps/bwm \

LIB             =twl

OBJS            =\
                application \
                color \
                event \
                eventKey \
                eventMouse \
                eventRedraw \
                eventResize \
                font3x5 \
                font \
                frame \
                glWidget \
                pushButton \
                rect \
                widget \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
