include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


#INCL_PATH       =\
#                ../libpng \

LIB             =twl

OBJS            =\
                application \
                color \
                event \
                eventKey \
                eventMouse \
                eventRedraw \
                eventResize \
                font3x5 \
                font \
                frame \
                glWidget \
                mouse \
                pixmap \
                pushButton \
                rect \
                widget \
                window \
                windowManager \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
