#INCL_PATH       =\
#                ../libpng \

LIB             =twl

OBJS            =\
                application \
                color \
                desktop \
                event \
                eventKey \
                eventMouse \
                eventRedraw \
                font3x5 \
                font \
                frame \
                mouse \
                pixmap \
                pushButton \
                rect \
                widget \
                window \
                windowImpl \
                windowManager \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
