LIB		=kernel
OBJS		=\
		 arch \
		 interrupt \
		 interruptManager \
		 timerManager \
		 video \
		 fileio \
		 bricks \
		 timeValue\

#		 task \
		 taskManager \

include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
