include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


OBJ             =arch
OBJS            =\
                arch \


include $(BRICKS_ROOT)/include/makeinclude/rules.kernel
