include $(BRICKS_ROOT)/arch/$(ARCH)/config.$(TARGET)


LIB             =arch
OBJS            =\
                arch \
                ps2Video \
                support \

DEFINITIONS-$(CONFIG_MULTITASKING) += CONFIG_MULTITASKING


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
