include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


OBJ             =apps
OBJS            =\
                testGL \
                testGLF \
                testGLFx \
                pyramid \
                cube \
                crate \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
