LIB             =arch
OBJS            =\
                entry \
                arch \
                aspace \
                descriptor \
                irq \
                isrWrapper \
                keyboard \
                mmap \
                support \
                task \
                video \


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
