LIB             =arch
OBJS            =\
                entry \
                isrWrapper \
                support \
                i386Arch \
                i386Video \
                i386Keyboard \
                irq \
                gdt \
                idt \


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
