LIB             =arch
OBJS            =\
                arch \
                entry \
                gdt \
                idt \
                irq \
                isrWrapper \
                keyboard \
                support \
                video \


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
