ifeq ($(TARGET),gba)
  ARCH = arm
endif
ifeq ($(TARGET),nds7)
  ARCH = arm
endif
ifeq ($(TARGET),nds9)
  ARCH = arm
endif
ifeq ($(TARGET),ps2)
  ARCH = mips
endif
ifeq ($(TARGET),i386)
  ARCH = i386
endif

DIRS = $(ARCH)


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
