ifeq ($(TARGET),gba)
  DIRS = arm
endif
ifeq ($(TARGET),nds7)
  DIRS = arm
endif
ifeq ($(TARGET),nds9)
  DIRS = arm
endif
ifeq ($(TARGET),ps2)
  DIRS = mips
endif
ifeq ($(TARGET),i386)
  DIRS = i386
endif


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
