include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


LIB             =arch
OBJS            =\
                arch \
                task \


include $(BRICKS_ROOT)/include/makeinclude/rules.kernel
