LIB             =gl
OBJS            =\
                context \
                egl \
                gl \
                matrix \
                softGLF \
                softGLFx \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
