include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


LIB             =gl
OBJS            =\
                context \
                gl \
                glMatrix \
                glu \
                glut \
                textures \
                rasterCommon \
                rasterScanline \
                mathlib \
                render \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
