include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


LIB             =gl
OBJS            =\
                CDDA \
                CFuncDebug \
                gl \
                glProfiling \
                glu \
                glut \
                mathlib \
                rasterCommon \
                rasterScanline \
                render \
                renderContext \
                renderMatrix \
                textures \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
