LIB             =z

OBJS            =\
                adler32 \
                compress \
                crc32 \
                deflate \
                gzio \
                infback \
                inffast \
                inflate \
                inftrees \
                trees \
                uncompr \
                zutil \


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
