include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


LIB             =apps
OBJS            =\
                test \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
