#LIBS            +=\
                archnds \

LIB             =arch
OBJS            =\
                support \
                isr \
                arch \
                irq \


INCL_PATH       +=\
                ../common \


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
