LIBS		+=\
		 archnds \
		 archarm \

LIB		=arch
OBJS		=\
                 support \
		 isr\
		 ds7Arch\
		 ds7IRQ\


INCLUDES	+=\
		 -I$(DEVKITPRO)/libnds/include\
		 -I../common\


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
