LIBS		+=\
		 archnds \
		 archarm \

LIB		=arch
OBJS		=\
                 support \
		 isr\
		 ds7Arch\
		 ds7IRQ\


INCL_PATH	+=\
		 $(DEVKITPRO)/libnds/include\
		 ../common\


include $(BRICKS_ROOT)/include/makeinclude/rules.common.GNU
