include $(BRICKS_ROOT)/kernel/include/include-$(ARCH)/include-$(TARGET)/asm/arch/config.make


OBJ             =apps
OBJS            =\
                main \
                raytracer \
                scene \


include $(BRICKS_ROOT)/include/makeinclude/rules.user
